name: Docker Image CI For GHCR

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-22.04
    env:
      GITHUB_USERNAME: ${{ env.GITHUB_USERNAME }}
      GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      PYTHON_VERSION: ${{ env.PYTHON_VERSION }}
      PYTORCH_VERSION: ${{ env.PYTORCH_VERSION }}
      IMAGE_BASE: ${{ env.IMAGE_BASE }}
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Build and push image
        run: |
          docker login ghcr.io -u $GITHUB_USERNAME -p $GITHUB_TOKEN
          docker build . \
            --build-arg PYTHON_VERSION=$PYTHON_VERSION \
            --build-arg PYTORCH_VERSION=$PYTORCH_VERSION \
            --build-arg IMAGE_BASE=$IMAGE_BASE \
            --tag ghcr.io/$GITHUB_USERNAME/comfyui-fluxvideo-ghcr:latest
          docker push ghcr.io/$GITHUB_USERNAME/comfyui-fluxvideo-ghcr:latest