name: Docker Image CI

on:
  push:

    branches: [ \"main\" ]
  pull_request:
    branches: [ \"main\" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build and push image
        run: |
          docker login --username tapchoilk123 --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/tapchoilk123/comfyui-fluxvideo-ghcr:latest
          docker push ghcr.io/tapchoilk123/comfyui-fluxvideo-ghcr:latest'
